"""Generate the README's lineage diagram from dbt's manifest.

The diagram is derived from the compiled project, not drawn by hand: every edge
comes from a real `ref()`/`source()` in `target/manifest.json`, so it cannot show
a dependency the code does not have. Re-run after adding or rewiring models:

    dbt compile            # refresh target/manifest.json
    python scripts/generate_lineage.py --check    # CI-style: fail if stale
    python scripts/generate_lineage.py            # rewrite the README block

The output is written between the LINEAGE markers in ../README.md.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve().parent
MANIFEST = HERE.parent / "target" / "manifest.json"
README = HERE.parent.parent / "README.md"
BEGIN = "<!-- BEGIN LINEAGE (generated by austender_project/scripts/generate_lineage.py) -->"
END = "<!-- END LINEAGE -->"

# Folder under models/ -> (subgraph id, label). Order sets left-to-right layout.
LAYERS = [
    ("source", "SRC", "BRONZE — raw, all STRING"),
    ("staging", "STG", "SILVER — staging"),
    ("silver", "SLV", "SILVER — cleansed"),
    ("gold", "GLD", "GOLD — star schema"),
    ("mart", "MRT", "MART — consumption"),
    ("other", "OTH", "Snapshots &amp; seeds"),
]


def layer_of(node: dict) -> str:
    """Classify by the model's folder, which is what the README's layers mean."""
    if node["resource_type"] == "source":
        return "source"
    parts = Path(node["original_file_path"]).parts
    if node["resource_type"] in ("snapshot", "seed"):
        return "other"
    for folder in ("staging", "silver", "gold", "mart"):
        if folder in parts:
            return folder
    return "other"


def build() -> str:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    graph: dict[str, dict] = {}
    graph.update({k: v for k, v in manifest["nodes"].items()
                  if v["resource_type"] in ("model", "snapshot", "seed")})
    graph.update(manifest["sources"])

    buckets: dict[str, list[str]] = {key: [] for _, key, _ in
                                     [(a, b, c) for a, b, c in LAYERS]}
    by_layer_key = {folder: key for folder, key, _ in LAYERS}
    for uid, node in graph.items():
        buckets[by_layer_key[layer_of(node)]].append(uid)

    lines = ["```mermaid", "flowchart LR"]
    for folder, key, label in LAYERS:
        members = sorted(buckets[key], key=lambda u: graph[u]["name"])
        if not members:
            continue
        lines.append(f"    subgraph {key}[\"{label}\"]")
        for uid in members:
            node = graph[uid]
            shape = ("([{}])" if node["resource_type"] == "source"
                     else "[({})]" if node["resource_type"] in ("snapshot", "seed")
                     else "[{}]")
            lines.append(f"        {node['name']}{shape.format(node['name'])}")
        lines.append("    end")

    edges = []
    for uid, node in graph.items():
        for dep in node.get("depends_on", {}).get("nodes", []):
            if dep in graph:
                edges.append(f"    {graph[dep]['name']} --> {node['name']}")
    lines.extend(sorted(set(edges)))
    lines.append("```")

    counts = {key: len(v) for key, v in buckets.items() if v}
    total = sum(counts.values())
    lines.append("")
    lines.append(f"*{total} nodes, {len(set(edges))} edges — generated from "
                 "`target/manifest.json`, so every arrow is a real `ref()`.*")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the README block is out of date (for CI)")
    args = ap.parse_args()

    if not MANIFEST.exists():
        print(f"No manifest at {MANIFEST} — run `dbt compile` first.")
        sys.exit(1)

    block = build()
    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"Markers not found in {README}. Add:\n{BEGIN}\n{END}")
        sys.exit(1)

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = f"{head}{BEGIN}\n{block}\n{END}{tail}"

    if args.check:
        if updated != text:
            print("README lineage block is stale — run generate_lineage.py.")
            sys.exit(1)
        print("README lineage block is up to date.")
        return

    if updated == text:
        print("README lineage block already up to date.")
        return
    README.write_text(updated, encoding="utf-8")
    print(f"Updated the lineage block in {README}.")


if __name__ == "__main__":
    main()
